name: Monorepo Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if subdiretorio1 has changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q subdiretorio1/; then
            echo "Changes detected in subdiretorio1"
          else
            echo "No changes detected in subdiretorio1, skipping pipeline"
            exit 0
          fi

      - name: Install dependencies and build subdiretorio1
        run: |
          cd subdiretorio1
          npm ci
          npm run build

      - name: Check if subdiretorio2 has changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q subdiretorio2/; then
            echo "Changes detected in subdiretorio2"
          else
            echo "No changes detected in subdiretorio2, skipping pipeline"
            exit 0
          fi

      - name: Install dependencies and build subdiretorio2
        run: |
          cd subdiretorio2
          npm ci
          npm run build

      - name: Push changes to GitHub
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update subdiretorios"
          commit_options: '--no-verify'
          commit_user_email: saulo.oliveira@hotmart.com
          commit_user_name: "Saulo Oliveira"
          branches: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
